% plot_WRM_vs_WIM_IPP.m - Plot of absorption-based vs wavelength-integrated IPP calculation
%
% Syntax:  plot_WRM_vs_WIM_IPP
%
% Inputs:
%    1) Folder location with with integrated primary prodution (IPP) data
%
% Outputs:
%    1) '*.mat' file with compiled productivity data generated by
%    'pp_daily_algorithm.m' or 'pp_daily_algorithm_vertical_profile.m'
%   
% Other m-files required: None
%
% MAT-files required: 
%   1) Compiled integrated primary production data generated by
%    'pp_daily_algorithm.m' or 'pp_daily_algorithm_vertical_profile.m'
%    ('all_IPP_table.mat' or 'all_IPP_table_profile.mat')
%
% Author: Steven E. Lohrenz, Ph.D., biological oceanography
% School for Marine Science and Technology, University of Massachusetts Dartmouth
% email address: slohrenz@umassd.edu
% Website: http://www.umassd.edu/smast/
% Last revision: 9 Dec 2025

%% ------------- BEGIN CODE --------------%

folderpath='\';
load([folderpath,'P-E\all_IPP_table.mat']); % Profiles estimated from surface 
%   values of P-E and aph, and vertical irradiance profile
load([folderpath,'P-E\all_IPP_table_profile.mat']); % Profiles estimated 
%   from surface values of P-E,vertical profiles of aph based on relationship
%   to CTD fluorescence, and vertical irradiance profile

%% 
% Estimated IPP using surface observations of aph and P-E parameters, and
%   vertical irradiance profile from HyperPro
figure(1);
clf

ax_lim = 1.5;
ax_min = 0.06;

% Plot wavelength-resolved (WRM) vs. wavelength-integrated (WIM) IPP
hpp = plot(all_IPP_tab.WRM,all_IPP_tab.WIM,'ob','Linewidth',1.5);
hold on
h1to1 = plot([ax_min,ax_lim],[ax_min,ax_lim],':k','LineWidth',1.5);
box on
% Plot wavelength-resolved (WRM) vs. wavelength-resolved estimated (WRME) IPP
hppe = plot(all_IPP_tab.WRM,all_IPP_tab.WRME,'+m','Linewidth',1.5);
set(gca,'FontSize',12,'LineWidth',1.5,'YLim',[ax_min,ax_lim],'XLim',[ax_min,ax_lim], ...
    'XScale','log','YScale','log');

% Get stats for correlations
[R_IPP_WIM,P1] = corrcoef(log(all_IPP_tab.WRM),log(all_IPP_tab.WIM));
rtmeansq1 = rmse(all_IPP_tab.WRM,all_IPP_tab.WIM);
r_square_WIM = R_IPP_WIM(1,2).^2;
mean_percent_bias = mean(100.*(all_IPP_tab.WRM-all_IPP_tab.WIM)./all_IPP_tab.WRM);

[R_IPP_WRME,P2] = corrcoef(log(all_IPP_tab.WRM),log(all_IPP_tab.WRME));
rtmeansq2 = rmse(all_IPP_tab.WRM,all_IPP_tab.WRME);
r_square_WRME = R_IPP_WRME(1,2).^2;

ylabel('Wavelength-Integrated IPP (mol C m^{-2} h^{-1})','FontSize',14,'FontWeight','bold');
xlabel('Wavelength-Resolved IPP (mol C m^{-2} h^{-1})','FontSize',14,'FontWeight','bold');

legend([hpp,hppe,h1to1],{'WIM','WRME','1:1 Line'},'FontSize',12,'Location','Southeast');

print([folderpath,'P-E\','wrm_vs_wim_ipp.tif'],'-dtiff','-r600');

%% Profile IPP data
% Estimated IPP using surface observations of P-E parameters, vertical 
%   irradiance profile from HyperPro, and vertical profile of aph estimated 
%   from correlation with CTD fluorescence
figure(2);
clf

hpp_wrm_pr = plot(all_IPP_tab.WRM,all_IPP_tab_profile.WRM,'ob','Linewidth',1.5);
hold on
h1to1 = plot([ax_min,ax_lim],[ax_min,ax_lim],':k','LineWidth',1.5);
box on
% hpp_wim_pr = plot(all_IPP_tab.WIM,all_IPP_tab_profile.WIM,'+m','Linewidth',1.5);
set(gca,'FontSize',12,'LineWidth',1.5,'YLim',[ax_min,ax_lim],'XLim',[ax_min,ax_lim], ...
    'XScale','log','YScale','log');

% Get correlation stats
[R_IPP_WRM_profile,P3] = corrcoef(log(all_IPP_tab.WRM),log(all_IPP_tab_profile.WRM));
rtmeansq1 = rmse(all_IPP_tab.WRM,all_IPP_tab_profile.WRM);
r_square_WRM_profile = R_IPP_WRM_profile(1,2).^2;
mean_percent_bias_profile = mean(100.*(all_IPP_tab.WRM-all_IPP_tab_profile.WRM)./all_IPP_tab.WRM);

[R_IPP_WIM_profile,P4] = corrcoef(log(all_IPP_tab.WIM),log(all_IPP_tab_profile.WIM));
rtmeansq2 = rmse(all_IPP_tab.WIM,all_IPP_tab_profile.WIM);
r_square_WIM_profile = R_IPP_WIM_profile(1,2).^2;

ylabel('IPP Profile (mol C m^{-2} h^{-1})','FontSize',14,'FontWeight','bold');
xlabel('IPP Surface Only (mol C m^{-2} h^{-1})','FontSize',14,'FontWeight','bold');

legend([hpp_wrm_pr,h1to1],{'WRM vs WRM profile','1:1 Line'},'FontSize',12,'Location','Southeast');

print([folderpath,'P-E\','wrm_vs_profile_ipp.tif'],'-dtiff','-r600');



disp('Completed');
